from .osidb_api_v1_affects_bulk_create import *
from .osidb_api_v1_affects_bulk_destroy import *
from .osidb_api_v1_affects_bulk_update import *
from .osidb_api_v1_affects_create import *
from .osidb_api_v1_affects_cvss_scores_create import *
from .osidb_api_v1_affects_cvss_scores_destroy import *
from .osidb_api_v1_affects_cvss_scores_list import *
from .osidb_api_v1_affects_cvss_scores_retrieve import *
from .osidb_api_v1_affects_cvss_scores_update import *
from .osidb_api_v1_affects_destroy import *
from .osidb_api_v1_affects_list import *
from .osidb_api_v1_affects_retrieve import *
from .osidb_api_v1_affects_update import *
from .osidb_api_v1_alerts_list import *
from .osidb_api_v1_alerts_retrieve import *
from .osidb_api_v1_audit_list import *
from .osidb_api_v1_audit_retrieve import *
from .osidb_api_v1_audit_update import *
from .osidb_api_v1_flaws_acknowledgments_create import *
from .osidb_api_v1_flaws_acknowledgments_destroy import *
from .osidb_api_v1_flaws_acknowledgments_list import *
from .osidb_api_v1_flaws_acknowledgments_retrieve import *
from .osidb_api_v1_flaws_acknowledgments_update import *
from .osidb_api_v1_flaws_comments_create import *
from .osidb_api_v1_flaws_comments_list import *
from .osidb_api_v1_flaws_comments_retrieve import *
from .osidb_api_v1_flaws_create import *
from .osidb_api_v1_flaws_cvss_scores_create import *
from .osidb_api_v1_flaws_cvss_scores_destroy import *
from .osidb_api_v1_flaws_cvss_scores_list import *
from .osidb_api_v1_flaws_cvss_scores_retrieve import *
from .osidb_api_v1_flaws_cvss_scores_update import *
from .osidb_api_v1_flaws_list import *
from .osidb_api_v1_flaws_package_versions_create import *
from .osidb_api_v1_flaws_package_versions_destroy import *
from .osidb_api_v1_flaws_package_versions_list import *
from .osidb_api_v1_flaws_package_versions_retrieve import *
from .osidb_api_v1_flaws_package_versions_update import *
from .osidb_api_v1_flaws_promote_create import *
from .osidb_api_v1_flaws_references_create import *
from .osidb_api_v1_flaws_references_destroy import *
from .osidb_api_v1_flaws_references_list import *
from .osidb_api_v1_flaws_references_retrieve import *
from .osidb_api_v1_flaws_references_update import *
from .osidb_api_v1_flaws_reject_create import *
from .osidb_api_v1_flaws_retrieve import *
from .osidb_api_v1_flaws_update import *
from .osidb_api_v1_manifest_retrieve import *
from .osidb_api_v1_schema_retrieve import *
from .osidb_api_v1_status_retrieve import *
from .osidb_api_v1_trackers_create import *
from .osidb_api_v1_trackers_list import *
from .osidb_api_v1_trackers_retrieve import *
from .osidb_api_v1_trackers_update import *
from .osidb_healthy_retrieve import *
from .osidb_whoami_retrieve import *
