from enum import Enum


class OsidbApiV2FlawsListMajorIncidentState(str, Enum):
    EXPLOITS_KEV_APPROVED = "EXPLOITS_KEV_APPROVED"
    EXPLOITS_KEV_REJECTED = "EXPLOITS_KEV_REJECTED"
    EXPLOITS_KEV_REQUESTED = "EXPLOITS_KEV_REQUESTED"
    MAJOR_INCIDENT_APPROVED = "MAJOR_INCIDENT_APPROVED"
    MAJOR_INCIDENT_REJECTED = "MAJOR_INCIDENT_REJECTED"
    MAJOR_INCIDENT_REQUESTED = "MAJOR_INCIDENT_REQUESTED"
    MINOR_INCIDENT_APPROVED = "MINOR_INCIDENT_APPROVED"
    MINOR_INCIDENT_REJECTED = "MINOR_INCIDENT_REJECTED"
    MINOR_INCIDENT_REQUESTED = "MINOR_INCIDENT_REQUESTED"
    VALUE_0 = ""

    def __str__(self) -> str:
        return str(self.value)
