from enum import Enum


class SourceEnum(str, Enum):
    NOVALUE = "NOVALUE"
    ADOBE = "ADOBE"
    APPLE = "APPLE"
    BUGTRAQ = "BUGTRAQ"
    BUGZILLA = "BUGZILLA"
    CERT = "CERT"
    CUSTOMER = "CUSTOMER"
    CVE = "CVE"
    DEBIAN = "DEBIAN"
    DISTROS = "DISTROS"
    FULLDISCLOSURE = "FULLDISCLOSURE"
    GENTOO = "GENTOO"
    GIT = "GIT"
    GOOGLE = "GOOGLE"
    HW_VENDOR = "HW_VENDOR"
    INTERNET = "INTERNET"
    LKML = "LKML"
    MAGEIA = "MAGEIA"
    MIT = "MIT"
    MOZILLA = "MOZILLA"
    OSSSECURITY = "OSSSECURITY"
    OPENSSL = "OPENSSL"
    ORACLE = "ORACLE"
    PHP = "PHP"
    PIDGIN = "PIDGIN"
    REDHAT = "REDHAT"
    RESEARCHER = "RESEARCHER"
    SECALERT = "SECALERT"
    SKO = "SKO"
    SECUNIA = "SECUNIA"
    SUN = "SUN"
    SUSE = "SUSE"
    TWITTER = "TWITTER"
    UBUNTU = "UBUNTU"
    UPSTREAM = "UPSTREAM"
    VENDORSEC = "VENDORSEC"
    XEN = "XEN"

    def __str__(self) -> str:
        return str(self.value)
